#this is the configuration file of the Optimisation plugin

title = "PyMoDAQ's optical 2D shaping package configuration file"

[sizing]
square_size = true
binning = 2  # the shape of the fields will be binned accordingly as (1x1), (2x2), etc... (should be power of 2)

[setup]
wavelength_nm = 515
setup_type = ['2f', '4f', 'no_lens'] #readonly set from the chosen algorithm

    [setup.no_lens]
    lengths = [200, ] #length in mm between the various elements of the setup (here between SLM and target as there is no lens)

    [setup.2f]
    lengths = [100, 100]
    focals = [100,] #focal length in mm in the setup (here only one lens)

    [setup.4f]
    lengths = [100, 100, 150, 150]
    focals = [100, 150]

[SLM]
default_slm = ["PLUTO", "LC2012"] #first elet in the list used as default


[SLM.PLUTO]
width = 1920
height = 1080
pixel_size = 8  # in micrometer
has_internal_calibration = true
use_internal_calibration = false

[SLM.LC2012]
width = 1024
height = 768
pixel_size = 36   # in micrometer
has_internal_calibration = true
use_internal_calibration = false

[target]
default_loader = ["ImageFiles"] #will be populated at startup from the reading of the factory
 #first elet in the list used as default

[input]
default_loader = ["GaussianIntensity"] #will be populated at startup from the reading of the factory
 #first elet in the list used as default

    [input.gaussian]
    fwhm_x = 7000  #um
    fwhm_y = 7000  #um

    [input.laguerre]
    waist = 1000  # um
    radial_index = 3
    azimutal_index = 4

    [input.ferris]
    waist = 800  # um
    azimutal_index_1 = 3
    azimutal_index_2 = 11
    alpha = 5e-4


[algo]
default_algo = ['Gerchberg-Saxton']  #will be populated at startup from the reading of the factory
 #first elet in the list used as default
    [algo.crosstalk]
    apply = false
    value = 0.5

    [algo.phase_manipulation]
    apply = false
    wrap_value = 2 # in units of pi
    dynamic_value = [8, 10, 12, 16]

[corrections]
    [corrections.actuators]
    focal_length = true

    [corrections.zernike]
    order_max = 5

        [corrections.zernike.actuators]
        n0 = false
        n1 = false
        n2 = true
        n3 = true
        n4 = false

