#this is the configuration file of the Optimisation plugin

title = "PyMoDAQ's optical 2D shaping package configuration file"

[setup]
wavelength_nm = 515
type = ['no_lens', '2f', '4f']

    [setup.no_lens]
    slm_target_mm = 200

    [setup.2f]
    slm_lens_length_mm = 100
    lens_target_mm = 100
    lens_focal_mm = 100

    [setup.4f]
    slm_lens1_length_mm = 100
    lens1_mask_mm = 100
    lens1_focal_mm = 100
    mask_lens2_mm = 100
    lens2_target_mm = 100

    mask = true
    mask_center_mm = [0, 0]
    masr_size_mm = [1, 1]

[SLM]
default_slm = "PLUTO"
[SLM.PLUTO]
width = 1920
height = 1080
pixel_size = 8  # in micrometer


[SLM.LC2012]
width = 1024
height = 768
pixel_size = 36   # in micrometer


[target]
default_loader = "ImageFileLoader"

[input]
default_loader = "GaussianIntensityLoader"

    [input.gaussian]
    fwhm_x = 7.0  #mm
    fwhm_y = 7.0  #mm

    [input.laguerre]
    waist = 3.0  # mm
    radial_index = 3
    azimutal_index = 4


[algo]
default_algo = 'Gerchberg-Saxton'


[corrections]
    [corrections.actuators]
    focal_length = true

    [corrections.zernike]
    order_max = 5

        [corrections.zernike.actuators]
        n0 = false
        n1 = false
        n2 = true
        n3 = true
        n4 = false

