#this is the configuration file of the Optimisation plugin

title = "PyMoDAQ's optical 2D shaping package configuration file"

[sizing]
binning = 8  # the shape of the fields will be binned accordingly as (1x1), (2x2), etc... (should be power of 2)
padding = 2048 # the padding during calculation. if 0, not a power of 2 and lower than the slm size, the padding value will be the first power of n bigger than the max size of the SLM


[setup]
wavelength_nm = 515
setup_type = ['2f', '4f', 'no_lens'] #readonly set from the chosen algorithm

    [setup.no_lens]
    lengths = [200, ] #length in mm between the various elements of the setup (here between SLM and target as there is no lens)

    [setup.2f]
    lengths = [100, 100]
    focals = [100,] #focal length in mm in the setup (here only one lens)

    [setup.4f]
    lengths = [100, 100, 150, 150]
    focals = [100, 150]

[SLM]
default_slm = ["PLUTO", "LC2012"] #first elet in the list used as default


[SLM.PLUTO]
width = 1920
height = 1080
pixel_size = 8  # in micrometer


[SLM.LC2012]
width = 1024
height = 768
pixel_size = 36   # in micrometer


[target]
default_loader = ["ImageFileLoader"] #will be populated at startup from the reading of the factory
 #first elet in the list used as default

[input]
default_loader = ["GaussianIntensityLoader"] #will be populated at startup from the reading of the factory
 #first elet in the list used as default

    [input.gaussian]
    fwhm_x = 7.0  #mm
    fwhm_y = 7.0  #mm

    [input.laguerre]
    waist = 1.0  # mm
    radial_index = 3
    azimutal_index = 4

    [input.ferris]
    waist = 0.8  # mm
    azimutal_index_1 = 3
    azimutal_index_2 = 11
    alpha = 5e-4


[algo]
default_algo = ['Weighted Gerchberg-Saxton']  #will be populated at startup from the reading of the factory
 #first elet in the list used as default

[corrections]
    [corrections.actuators]
    focal_length = true

    [corrections.zernike]
    order_max = 5

        [corrections.zernike.actuators]
        n0 = false
        n1 = false
        n2 = true
        n3 = true
        n4 = false

